/**
 * Created by shao_ on 2017/6/15.
 */
//app

export const APP_PAGE_LOADING = 'APP_PAGE_LOADING'
export const APP_CONFIRM_SHOW = 'APP_CONFIRM_SHOW'


//home
export const HOME_ORDERS_ALL = 'HOME_ORDERS_ALL'
export const HOME_LOADING_ALL = 'HOME_LOADING_ALL'
export const HOME_ORDER_ALL_SKIP = 'HOME_ORDER_ALL_SKIP'
export const HOME_ALL_DONE = 'HOME_ALL_DONE'

export const HOME_ORDERS_PROCESSING = 'HOME_ORDERS_PROCESSING'
export const HOME_LOADING_PROCESSING = 'HOME_LOADING_PROCESSING'
export const HOME_ORDER_PROCESSING_SKIP = 'HOME_ORDER_PROCESSING_SKIP'
export const HOME_PROCESSING_DONE = 'HOME_PROCESSING_DONE'

export const HOME_ORDERS_UNPAID = 'HOME_ORDERS_UNPAID'
export const HOME_LOADING_UNPAID = 'HOME_LOADING_UNPAID'
export const HOME_ORDER_UNPAID_SKIP = 'HOME_ORDER_UNPAID_SKIP'
export const HOME_UNPAID_DONE = 'HOME_UNPAID_DONE'

export const HOME_ORDERS_PAID = 'HOME_ORDERS_PAID'
export const HOME_LOADING_PAID = 'HOME_LOADING_PAID'
export const HOME_ORDER_PAID_SKIP = 'HOME_ORDER_PAID_SKIP'
export const HOME_PAID_DONE = 'HOME_PAID_DONE'

export const HOME_ORDERS_SHIPPED = 'HOME_ORDERS_SHIPPED'
export const HOME_LOADING_SHIPPED = 'HOME_LOADING_SHIPPED'
export const HOME_ORDER_SHIPPED_SKIP = 'HOME_ORDER_SHIPPED_SKIP'
export const HOME_SHIPPED_DONE = 'HOME_SHIPPED_DONE'




export const HOME_ORDERS_CONFIRMED = 'HOME_ORDERS_CONFIRMED'
export const HOME_LOADING_CONFIRMED = 'HOME_LOADING_CONFIRMED'
export const HOME_ORDER_CONFIRMED_SKIP = 'HOME_ORDER_CONFIRMED_SKIP'
export const HOME_CONFIRMED_DONE = 'HOME_CONFIRMED_DONE'




export const HOME_ORDERS_CANCELED = 'HOME_ORDERS_CANCELED'
export const HOME_LOADING_CANCELED = 'HOME_LOADING_CANCELED'
export const HOME_ORDER_CANCELED_SKIP = 'HOME_ORDER_CANCELED_SKIP'
export const HOME_CANCELED_DONE = 'HOME_CANCELED_DONE'

export const HOME_ORDERS_STATUS_UPDATE = 'HOME_ORDERS_STATUS_UPDATE'



export const HOME_CHANGE_TAB = 'HOME_CHANGE_TAB'


export const DETAIL_LOAD_ORDER = 'DETAIL_LOAD_ORDER'
export const DETAIL_CONFIRM_ORDER = 'DETAIL_CONFIRM_ORDER'
export const DETAIL_CANCEL_ORDER = 'DETAIL_CANCEL_ORDER'
export const DETAIL_LOAD_LAST_REPLY = 'DETAIL_LOAD_LAST_REPLY'


//contact
export const CONTACT_LOAD_TICKET = 'CONTACT_LOAD_TICKET'
export const CONTACT_SEND_MESSAGE = 'CONTACT_SEND_MESSAGE'
export const CONTACT_SEND_IMAGE = 'CONTACT_SEND_IMAGE'
export const CONTACT_REVIEW_MSG = 'CONTACT_REVIEW_MSG'


//review
export const REVIEW_LOAD_COMMENT = 'REVIEW_LOAD_COMMENT'
export const REVIEW_SEND_COMMENT = 'REVIEW_SEND_COMMENT'
export const REVIEW_SENDING = 'REVIEW_SENDING'

export const REVIEW_GET_COMMENTS = 'REVIEW_GET_COMMENTS';

//tracking
export const TRACKING_LOAD = 'TRACKING_LOAD'
export const PACKAGE_TRACKING_LOAD = 'PACKAGE_TRACKING_LOAD'

//outside rate
export const OUTSITE_LOAD_SOICALS = 'OUTSITE_LOAD_SOICALS'
export const OUTSITE_LOAD_COUPON = 'OUTSITE_LOAD_COUPON'


export const HOME_GET_M1135 = 'HOME_GET_M1135'

export const ME_GET_YOU_LIKE_PRODUCTS = 'ME_GET_YOU_LIKE_PRODUCTS'
export const ME_GET_YOU_LIKE_SKIP = 'ME_GET_YOU_LIKE_SKIP'

export const CANCEL_ORDER_REASONS = 'CANCEL_ORDER_REASONS';

// return logistics
export const LOGISTICS_COMPANIES = 'LOGISTICS_COMPANIES';

export const GET_RETURN_LOGISTICS = 'GET_RETURN_LOGISTICS';








